columnSuffix: swmzeype
handle: fieldTwo
instructions: null
name: 'Matrix Field - Block Type One - Field Two'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
