columnSuffix: null
contentColumnType: string
fieldGroup: f948b9a4-6a4e-43da-84aa-65b91c0cd202 # Common
handle: matrixField
instructions: null
name: 'Matrix Field'
searchable: false
settings:
  contentTable: '{{%matrixcontent_matrixfield}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
